[phases.setup]
nixPkgs = ["python3", "playwright", "nodejs", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt",
  "playwright install --with-deps"
]

[phases.start]
cmd = "python superkick_bot.py"
